### ISSUE TITLE
Library conflicts with elm-lang/dom

### ISSUE THREAD

**Issue by arsduo** [danielnarey/elm-semantic-dom#1]
The readme notes that

> 10. I am aware that module naming scheme I chose conflicts with *elm-lang/dom*, which could be a problem but doesn't have to be. To avoid a compiler error when there is a need to manage DOM effects, I created *danielnarey/elm-semantic-effects* to wrap *elm-lang/dom*. When the two "dom" are not both listed as imports in the `elm-package.json` file, there is no compiler error, even if both packages are dependencies.

This choice has several downsides:

* It makes it harder to migrate to the `Ui` library for existing applications that use `Dom` already.
* It raises the perceived risks of adopting the Modular Ui framework (I can only speak for myself, but I'd be wary of adopting a framework that blocks packages released by the language maintainer).
* It puts you on the hook to match all the functionality in the `Dom` library, which could end up being a significant amount of work if that library expands, and that means that... 
* It puts your users in a bind -- if life changes and you stop maintaining `elm-semantic-effects`, users will be unable to fall back on the core `Dom` library in the event Elm 1.4 in 2021 releases some complex and important new functionality.

Supplanting a library's first-party libraries is a big commitment -- you'll need to mirror any changes to that library, and moreover do that roughly at the same time updates to that library get released to avoid getting in your users' way. `elm-lang/dom` is pretty small at the  moment, so that might be manageable, but `elm-lang/navigation` is much larger and more likely to change (fortunately we're not blocked from using that library directly, though changes to it could require changes to `elm-semantic-effects`).

Given all that, what do you think of renaming this to `SemanticDom`? That matches the repo name and the general theme of semantic tooling, and it would leave your users free to choose whichever of the first-party `dom` library or `elm-semantic-effects` library best meets their needs.

This would obviously be a big change and not one that would happen right away, but hopefully this can get a discussion started.

**Comment by danielnarey** [comment]
1. I agree with you on these points. I'm working through some ideas for the next major release in the interest of lowering barriers to adoption. Whether it is just a name change here or there is some restructuring of the current packages, the conflict of module names will be resolved. 

2. There's a larger issue here that will need to be addressed by the elm-lang core developers as the community grows. Because module names need to be short and ought to be intuitive, not allowing the same module name to be used by multiple packages imported in a given build presents challenges beyond this one case (as discussed [here](https://www.reddit.com/r/elm/comments/6dho6g/should_we_be_using_prefixed_module_names/)).

3. I created a [modular-ui-roadmap](https://github.com/danielnarey/modular-ui-roadmap) repo where I will outline next steps and invite feedback. I encourage you to follow this repo and to open an issue there if you have more general ideas/suggestions that aren't specific to problems with the current implementation. My timeline for releasing the next major version is one to two months.
